# Generated by Django 5.1 on 2024-11-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autenticaciones", "0002_remove_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
